/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AdminInternalPage;

import LoginandRegister.LoginForm;
import Session.Session;
import config.config;
import javax.swing.JOptionPane;
public class UserForm extends javax.swing.JFrame {
  private config conf = new config();

    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
        loadSessionInfo(); // pre-fill fields from logged-in user session
        label1.setText("Edit Your Profile");
        st_label.setText("SAVE");
    }

    public UserForm(String add, Object object, Object object0, Object object1, Object object2, Object object3) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstnamefield = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        ex = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        st_label = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        lastnamefield = new javax.swing.JTextField();
        lastname = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        passwordfield = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        useername = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();

        firstnamefield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        firstnamefield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstnamefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 234, 234), 2));
        firstnamefield.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(29, 45, 61));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 234, 234), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(55, 86, 93));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 234, 234), 3));
        jPanel2.setLayout(null);

        label1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(239, 234, 234));
        label1.setText("Label");
        jPanel2.add(label1);
        label1.setBounds(0, 0, 300, 40);

        ex.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        ex.setForeground(new java.awt.Color(239, 234, 234));
        ex.setText("Exit");
        jPanel2.add(ex);
        ex.setBounds(510, 0, 40, 40);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (2).png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(550, 0, 40, 40);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        add.setBackground(new java.awt.Color(55, 86, 93));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_label.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        st_label.setForeground(new java.awt.Color(239, 234, 234));
        st_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        st_label.setText("Label");
        add.add(st_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 20));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 100, 40));

        id.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(239, 234, 234));
        id.setText("ID:");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, 30));

        firstname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(239, 234, 234));
        firstname.setText("First Name:");
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, 30));

        lastnamefield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lastnamefield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastnamefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 234, 234), 2));
        lastnamefield.setOpaque(false);
        jPanel1.add(lastnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, 30));

        lastname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(239, 234, 234));
        lastname.setText("Last Name:");
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 90, 30));

        email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(239, 234, 234));
        email.setText("Email:");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, 30));

        idfield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 234, 234), 2));
        idfield.setEnabled(false);
        idfield.setOpaque(false);
        jPanel1.add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, 30));

        passwordfield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        passwordfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 234, 234), 2));
        passwordfield.setOpaque(false);
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 210, 30));

        password.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(239, 234, 234));
        password.setText("Password:");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 90, 30));

        emailfield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        emailfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 234, 234), 2));
        emailfield.setOpaque(false);
        jPanel1.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 210, 30));

        useername.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        useername.setForeground(new java.awt.Color(239, 234, 234));
        useername.setText("Username:");
        jPanel1.add(useername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 90, 30));

        usernamefield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        usernamefield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernamefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 234, 234), 2));
        usernamefield.setOpaque(false);
        jPanel1.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
         // Validate fields
        String fn = firstnamefield.getText().trim();
        String ln = lastnamefield.getText().trim();
        String em = emailfield.getText().trim();
        String un = usernamefield.getText().trim();
        String pw = passwordfield.getText().trim();

        if (fn.isEmpty() || ln.isEmpty() || em.isEmpty() || un.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "First Name, Last Name, Email, and Username are required.",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Basic email format check
        if (!em.contains("@") || !em.contains(".")) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid email address.",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get current user ID from session
        Session session = Session.getInstance();
        int userId = session.getUserId();

        // Update user in database
        if (pw.isEmpty()) {
            // Don't change password if field is empty
            conf.updateRecord(
                "UPDATE tbl_users SET firstname=?, lastname=?, email=?, username=? WHERE id=?",
                fn, ln, em, un, userId
            );
        } else {
            // Update password too if user typed a new one
            conf.updateRecord(
                "UPDATE tbl_users SET firstname=?, lastname=?, email=?, username=?, password=? WHERE id=?",
                fn, ln, em, un, pw, userId
            );
        }

        // Update the session with new data
        session.login(userId, un, fn, ln, em, session.getUserType());

        JOptionPane.showMessageDialog(this,
            "Profile updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Go back to Profile page to show updated info
        AdminInternalPage.Profile p = new AdminInternalPage.Profile();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
      
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
      
    }//GEN-LAST:event_addMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
       int confirm = JOptionPane.showConfirmDialog(this,
            "Discard changes and go back?", "Confirm Exit", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            AdminInternalPage.Profile p = new AdminInternalPage.Profile();
            p.setVisible(true);
            this.dispose();
        }
    
    }//GEN-LAST:event_exitMouseClicked
  
    // ── Pre-fill all fields from the logged-in user's session ───────────────
    private void loadSessionInfo() {
        Session session = Session.getInstance();
        if (session.isLoggedIn()) {
            idfield.setText(String.valueOf(session.getUserId()));
            firstnamefield.setText(session.getFirstname());
            lastnamefield.setText(session.getLastname());
            emailfield.setText(session.getEmail());
            usernamefield.setText(session.getUsername());
            // Leave password blank — user can type a new one if they want to change it
            passwordfield.setText("");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         Session session = Session.getInstance();
        if (!session.isLoggedIn()) {
            JOptionPane.showMessageDialog(null, 
                "Please login first!", 
                "Unauthorized Access", 
                JOptionPane.WARNING_MESSAGE);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginForm().setVisible(true);
                }
            });
            return;
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JLabel email;
    public javax.swing.JTextField emailfield;
    private javax.swing.JLabel ex;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel firstname;
    public javax.swing.JTextField firstnamefield;
    private javax.swing.JLabel id;
    public javax.swing.JTextField idfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lastname;
    public javax.swing.JTextField lastnamefield;
    private javax.swing.JLabel password;
    public javax.swing.JTextField passwordfield;
    public javax.swing.JLabel st_label;
    private javax.swing.JLabel useername;
    public javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables

}