/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import AdminInternalPage.Profile;
import Session.Session;
import config.config;
import javax.swing.JOptionPane;
import LoginandRegister.LoginForm;

/**
 *
 * @author ashlaran
 */
public class CreateBooking extends javax.swing.JFrame {

    
    private config conf = new config();

    /**
     * Creates new form CreateBooking
     */
    public CreateBooking() {
        initComponents();
        loadSessionInfo();        // pre-fill username label from session
    }

    // Load logged-in user's name into the sidebar label
    private void loadSessionInfo() {
        Session session = Session.getInstance();
        if (session.isLoggedIn()) {
            lblUsername.setText(session.getFullName());
        } else {
            lblUsername.setText("Staff");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listadmin = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        dashboard1 = new javax.swing.JLabel();
        availablecleanerpanel = new javax.swing.JPanel();
        availablecleaner = new javax.swing.JLabel();
        createbookingpanel3 = new javax.swing.JPanel();
        createbooking3 = new javax.swing.JLabel();
        viewservicespanel = new javax.swing.JPanel();
        viewservices = new javax.swing.JLabel();
        createbookingpanel = new javax.swing.JPanel();
        createbooking = new javax.swing.JLabel();
        servicepanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelbottom = new javax.swing.JPanel();
        createbookingpanel9 = new javax.swing.JPanel();
        createbooking9 = new javax.swing.JLabel();
        generatereceiptpanel = new javax.swing.JPanel();
        generatereceipt = new javax.swing.JLabel();
        createbookingpanel7 = new javax.swing.JPanel();
        createbooking7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        tasknote = new javax.swing.JLabel();
        servicefield = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        contactno = new javax.swing.JLabel();
        service = new javax.swing.JLabel();
        assigncleaner = new javax.swing.JLabel();
        bookingdate = new javax.swing.JLabel();
        mybookingspanel = new javax.swing.JPanel();
        mybookings = new javax.swing.JLabel();
        createbookingpanel5 = new javax.swing.JPanel();
        createbooking5 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        assigncleanerfield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        contactnofield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        bookingfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tasknotefield = new javax.swing.JTextArea();
        createpanel = new javax.swing.JPanel();
        add = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listadmin.setBackground(new java.awt.Color(55, 86, 93));
        listadmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        settings.setText("ACCOUNT");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        listadmin.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 10, 290, 50));

        lblUsername.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsername.setText("Staff");
        listadmin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        dashpanel.setBackground(new java.awt.Color(29, 45, 61));
        dashpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpanelMouseClicked(evt);
            }
        });
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        dashboard1.setForeground(new java.awt.Color(239, 234, 234));
        dashboard1.setText("Dashboard");
        dashpanel.add(dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        listadmin.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        availablecleanerpanel.setBackground(new java.awt.Color(29, 45, 61));
        availablecleanerpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availablecleanerpanelMouseClicked(evt);
            }
        });
        availablecleanerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        availablecleaner.setBackground(new java.awt.Color(29, 45, 61));
        availablecleaner.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        availablecleaner.setForeground(new java.awt.Color(239, 234, 234));
        availablecleaner.setText("Available Cleaner");
        availablecleanerpanel.add(availablecleaner, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, -1));

        createbookingpanel3.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanel3MouseClicked(evt);
            }
        });
        createbookingpanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking3.setBackground(new java.awt.Color(29, 45, 61));
        createbooking3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking3.setForeground(new java.awt.Color(239, 234, 234));
        createbooking3.setText("Create Booking");
        createbookingpanel3.add(createbooking3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        availablecleanerpanel.add(createbookingpanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        listadmin.add(availablecleanerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        viewservicespanel.setBackground(new java.awt.Color(29, 45, 61));
        viewservicespanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewservicespanelMouseClicked(evt);
            }
        });
        viewservicespanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewservices.setBackground(new java.awt.Color(29, 45, 61));
        viewservices.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        viewservices.setForeground(new java.awt.Color(239, 234, 234));
        viewservices.setText("View Services");
        viewservicespanel.add(viewservices, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        listadmin.add(viewservicespanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 40));

        createbookingpanel.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanelMouseClicked(evt);
            }
        });
        createbookingpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking.setBackground(new java.awt.Color(29, 45, 61));
        createbooking.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking.setForeground(new java.awt.Color(239, 234, 234));
        createbooking.setText("Create Booking");
        createbookingpanel.add(createbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        listadmin.add(createbookingpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 40));

        servicepanel.setBackground(new java.awt.Color(29, 45, 61));
        servicepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        listadmin.add(servicepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 40));

        getContentPane().add(listadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        jPanel4.setBackground(new java.awt.Color(232, 230, 230));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbottom.setBackground(new java.awt.Color(29, 45, 61));
        panelbottom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelbottomMouseClicked(evt);
            }
        });
        panelbottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbookingpanel9.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanel9MouseClicked(evt);
            }
        });
        createbookingpanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking9.setBackground(new java.awt.Color(29, 45, 61));
        createbooking9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking9.setForeground(new java.awt.Color(239, 234, 234));
        createbooking9.setText("Create Booking");
        createbookingpanel9.add(createbooking9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        panelbottom.add(createbookingpanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        jPanel4.add(panelbottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 180));

        generatereceiptpanel.setBackground(new java.awt.Color(29, 45, 61));
        generatereceiptpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generatereceiptpanelMouseClicked(evt);
            }
        });
        generatereceiptpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generatereceipt.setBackground(new java.awt.Color(29, 45, 61));
        generatereceipt.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        generatereceipt.setForeground(new java.awt.Color(239, 234, 234));
        generatereceipt.setText("Generate Receipt");
        generatereceiptpanel.add(generatereceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, -1));

        createbookingpanel7.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanel7MouseClicked(evt);
            }
        });
        createbookingpanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking7.setBackground(new java.awt.Color(29, 45, 61));
        createbooking7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking7.setForeground(new java.awt.Color(239, 234, 234));
        createbooking7.setText("Create Booking");
        createbookingpanel7.add(createbooking7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        generatereceiptpanel.add(createbookingpanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        jPanel4.add(generatereceiptpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        jPanel1.setBackground(new java.awt.Color(29, 45, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lg.setForeground(new java.awt.Color(239, 234, 234));
        lg.setText("Log Out");
        jPanel1.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 20));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (2).png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 20));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 50));

        tasknote.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tasknote.setText("Enter Task Note (Optional):");
        jPanel4.add(tasknote, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 190, 30));

        servicefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicefieldActionPerformed(evt);
            }
        });
        jPanel4.add(servicefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 140, 30));

        name.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        name.setText("Enter Name");
        jPanel4.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 100, 30));

        email.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        email.setText("Enter Email");
        jPanel4.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 100, 30));

        address.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        address.setText("Enter Address");
        jPanel4.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, 30));

        contactno.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        contactno.setText("Enter Contact #No.");
        jPanel4.add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 140, 30));

        service.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        service.setText("Enter Service");
        jPanel4.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 100, 30));

        assigncleaner.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        assigncleaner.setText("Assign Cleaner");
        jPanel4.add(assigncleaner, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 130, 30));

        bookingdate.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        bookingdate.setText("Enter Booking Date");
        jPanel4.add(bookingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 130, 30));

        mybookingspanel.setBackground(new java.awt.Color(29, 45, 61));
        mybookingspanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mybookingspanelMouseClicked(evt);
            }
        });
        mybookingspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mybookings.setBackground(new java.awt.Color(29, 45, 61));
        mybookings.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        mybookings.setForeground(new java.awt.Color(239, 234, 234));
        mybookings.setText("My Bookings");
        mybookingspanel.add(mybookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        createbookingpanel5.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanel5MouseClicked(evt);
            }
        });
        createbookingpanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking5.setBackground(new java.awt.Color(29, 45, 61));
        createbooking5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking5.setForeground(new java.awt.Color(239, 234, 234));
        createbooking5.setText("Create Booking");
        createbookingpanel5.add(createbooking5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        mybookingspanel.add(createbookingpanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        jPanel4.add(mybookingspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 40));

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        jPanel4.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 140, 30));

        assigncleanerfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assigncleanerfieldActionPerformed(evt);
            }
        });
        jPanel4.add(assigncleanerfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 140, 30));

        addressfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressfieldActionPerformed(evt);
            }
        });
        jPanel4.add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 140, 30));

        contactnofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnofieldActionPerformed(evt);
            }
        });
        jPanel4.add(contactnofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 150, 30));

        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        jPanel4.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 140, 30));

        bookingfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingfieldActionPerformed(evt);
            }
        });
        jPanel4.add(bookingfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 140, 30));

        tasknotefield.setColumns(20);
        tasknotefield.setRows(5);
        jScrollPane1.setViewportView(tasknotefield);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        createpanel.setBackground(new java.awt.Color(29, 45, 61));
        createpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createpanelMouseClicked(evt);
            }
        });
        createpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(239, 234, 234));
        add.setText("Create");
        createpanel.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        jPanel4.add(createpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 80, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
    Profile a = new Profile();
        a.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_settingsMouseClicked

    private void createbookingpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanelMouseClicked

    }//GEN-LAST:event_createbookingpanelMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
     int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to log out?",
            "Log Out", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Session.getInstance().logout();
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void servicefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicefieldActionPerformed

    private void viewservicespanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewservicespanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_viewservicespanelMouseClicked

    private void availablecleanerpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availablecleanerpanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_availablecleanerpanelMouseClicked

    private void createbookingpanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createbookingpanel3MouseClicked

    private void createbookingpanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createbookingpanel5MouseClicked

    private void mybookingspanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mybookingspanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mybookingspanelMouseClicked

    private void createbookingpanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createbookingpanel7MouseClicked

    private void generatereceiptpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generatereceiptpanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_generatereceiptpanelMouseClicked

    private void createbookingpanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createbookingpanel9MouseClicked

    private void panelbottomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbottomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelbottomMouseClicked

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void assigncleanerfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assigncleanerfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assigncleanerfieldActionPerformed

    private void addressfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressfieldActionPerformed

    private void contactnofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnofieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void bookingfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingfieldActionPerformed

    private void createpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createpanelMouseClicked
      
       
        // ── 1. Collect field values ──────────────────────────────────────────
        String customerName  = namefield.getText().trim();
        String customerEmail = emailfield.getText().trim();
        String customerAddr  = addressfield.getText().trim();
        String customerPhone = contactnofield.getText().trim();
        String serviceType   = servicefield.getText().trim();
        String cleanerName   = assigncleanerfield.getText().trim();
        String bookDate      = bookingfield.getText().trim();
        String taskNote      = tasknotefield.getText().trim();

        // ── 2. Validate required fields ──────────────────────────────────────
        if (customerName.isEmpty() || customerEmail.isEmpty() ||
            customerAddr.isEmpty() || customerPhone.isEmpty() ||
            serviceType.isEmpty()  || bookDate.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in all required fields:\n" +
                "Name, Email, Address, Contact No., Service, and Booking Date.",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ── 3. Get the logged-in staff's ID from the session ─────────────────
        Session session = Session.getInstance();
        if (!session.isLoggedIn()) {
            JOptionPane.showMessageDialog(this,
                "Session expired. Please log in again.",
                "Unauthorized", JOptionPane.ERROR_MESSAGE);
            new LoginForm().setVisible(true);
            this.dispose();
            return;
        }
        int staffId = session.getUserId(); // staff_id stored in tbl_bookings

        // ── 4. Insert booking into tbl_bookings ──────────────────────────────
        //    status is hardcoded to 'Pending' on every new booking
        conf.addRecord(
            "INSERT INTO tbl_bookings " +
            "(name, email, address, contact_no, service, assign_cleaner, " +
            " booking_date, task_note, staff_id, status) " +
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'Pending')",
            customerName,
            customerEmail,
            customerAddr,
            customerPhone,
            serviceType,
            cleanerName.isEmpty() ? null : cleanerName,
            bookDate,
            taskNote.isEmpty()    ? null : taskNote,
            staffId
        );

        // ── 5. Success feedback then clear the form ───────────────────────────
        JOptionPane.showMessageDialog(this,
            "Booking created successfully!\n" +
            "Status: Pending\n" +
            "Staff ID: " + staffId,
            "Booking Created", JOptionPane.INFORMATION_MESSAGE);

        // Clear fields for next entry
        namefield.setText("");
        emailfield.setText("");
        addressfield.setText("");
        contactnofield.setText("");
        servicefield.setText("");
        assigncleanerfield.setText("");
        bookingfield.setText("");
        tasknotefield.setText("");
    }//GEN-LAST:event_createpanelMouseClicked

    private void dashpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseClicked
        UserDash u = new UserDash();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Session session = Session.getInstance();
        if (!session.isLoggedIn()) {
            JOptionPane.showMessageDialog(null,
                "Please login first!",
                "Unauthorized Access",
                JOptionPane.WARNING_MESSAGE);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginForm().setVisible(true);
                }
            });
            return;
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel assigncleaner;
    private javax.swing.JTextField assigncleanerfield;
    private javax.swing.JLabel availablecleaner;
    private javax.swing.JPanel availablecleanerpanel;
    private javax.swing.JLabel bookingdate;
    private javax.swing.JTextField bookingfield;
    private javax.swing.JLabel contactno;
    private javax.swing.JTextField contactnofield;
    private javax.swing.JLabel createbooking;
    private javax.swing.JLabel createbooking3;
    private javax.swing.JLabel createbooking5;
    private javax.swing.JLabel createbooking7;
    private javax.swing.JLabel createbooking9;
    private javax.swing.JPanel createbookingpanel;
    private javax.swing.JPanel createbookingpanel3;
    private javax.swing.JPanel createbookingpanel5;
    private javax.swing.JPanel createbookingpanel7;
    private javax.swing.JPanel createbookingpanel9;
    private javax.swing.JPanel createpanel;
    private javax.swing.JLabel dashboard1;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel generatereceipt;
    private javax.swing.JPanel generatereceiptpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lg;
    private javax.swing.JPanel listadmin;
    private javax.swing.JLabel mybookings;
    private javax.swing.JPanel mybookingspanel;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namefield;
    private javax.swing.JPanel panelbottom;
    private javax.swing.JLabel service;
    private javax.swing.JTextField servicefield;
    private javax.swing.JPanel servicepanel;
    private javax.swing.JLabel settings;
    private javax.swing.JLabel tasknote;
    private javax.swing.JTextArea tasknotefield;
    private javax.swing.JLabel viewservices;
    private javax.swing.JPanel viewservicespanel;
    // End of variables declaration//GEN-END:variables
}
