/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Login.LoginForm;

/**
 *
 * @author ashlaran
 */
public class UserDash extends javax.swing.JFrame {

    private String loggedInUsername;

    /**
     private String loggedInUsername; // Store the logged-in username
    
    /**
     * Creates new form UserDash
     */
    public UserDash() {
        initComponents();
        this.loggedInUsername = "User"; // Default
    }
    
    /**
     * Constructor with username parameter
     */
    public UserDash(String username) {
        initComponents();
        this.loggedInUsername = username;
        lblUsername.setText("Welcome, " + username + "!"); // Display username
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        liststaff = new javax.swing.JPanel();
        exitpanel1 = new javax.swing.JPanel();
        LOGOUT = new javax.swing.JLabel();
        bookpanel = new javax.swing.JPanel();
        bookings = new javax.swing.JLabel();
        customerpanel = new javax.swing.JPanel();
        customer = new javax.swing.JLabel();
        assignpanel = new javax.swing.JPanel();
        assign = new javax.swing.JLabel();
        jobstatuspanel = new javax.swing.JPanel();
        jobstatus = new javax.swing.JLabel();
        messagepanel = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liststaff.setBackground(new java.awt.Color(204, 204, 204));
        liststaff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitpanel1MouseClicked(evt);
            }
        });
        exitpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGOUT.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LOGOUT.setText("LOGOUT");
        exitpanel1.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 20));

        liststaff.add(exitpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 40));

        bookpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookings.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        bookings.setText("BOOKINGS");
        bookpanel.add(bookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 20));

        liststaff.add(bookpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 40));

        customerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        customer.setText("CUSTOMERS");
        customerpanel.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        liststaff.add(customerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 40));

        assignpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assign.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        assign.setText("ASSIGN JOBS");
        assignpanel.add(assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        liststaff.add(assignpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 40));

        jobstatuspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jobstatus.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jobstatus.setText("JOB STATUS");
        jobstatuspanel.add(jobstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, -1));

        liststaff.add(jobstatuspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        messagepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        message.setText("MESSAGES");
        messagepanel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        liststaff.add(messagepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 40));

        lblUsername.setText("WELCOME, User!");
        liststaff.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(liststaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 490));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 620, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitpanel1MouseClicked
       LoginForm lf = new LoginForm();
       lf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_exitpanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel assign;
    private javax.swing.JPanel assignpanel;
    private javax.swing.JLabel bookings;
    private javax.swing.JPanel bookpanel;
    private javax.swing.JLabel customer;
    private javax.swing.JPanel customerpanel;
    private javax.swing.JPanel exitpanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jobstatus;
    private javax.swing.JPanel jobstatuspanel;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel liststaff;
    private javax.swing.JLabel message;
    private javax.swing.JPanel messagepanel;
    // End of variables declaration//GEN-END:variables
}
