/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import AdminInternalPage.Profile;
import LoginandRegister.LoginForm;
import Session.Session;
import javax.swing.JOptionPane;
/**
 *
 * @author ashlaran
 */
public class UserDash extends javax.swing.JFrame {

    private String loggedInUsername;

    /**
     private String loggedInUsername; // Store the logged-in username
    
    /**
     * Creates new form UserDash
     */
    public UserDash() {
        initComponents();
        this.loggedInUsername = "User"; // Default
         loadSessionInfo();  
    }
    
    /**
     * Constructor with username parameter
     */
    public UserDash(String username) {
        initComponents();
        this.loggedInUsername = username;
        lblUsername.setText("Welcome, " + username + "!"); // Display username
        loadSessionInfo(); 
    }
    private void loadSessionInfo() {
    Session session = Session.getInstance();
    if (session.isLoggedIn()) {
        // Display full name from session
        lblUsername.setText(session.getFullName() + "!");
        System.out.println("UserDash loaded for: " + session.getUsername());
    } else {
        lblUsername.setText("WELCOME!");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generatereceiptpanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generatereceiptpanel2.setBackground(new java.awt.Color(153, 255, 255));
        generatereceiptpanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generatereceiptpanel2MouseClicked(evt);
            }
        });
        generatereceiptpanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(generatereceiptpanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generatereceiptpanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generatereceiptpanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_generatereceiptpanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         Session session = Session.getInstance();
        if (!session.isLoggedIn()) {
            JOptionPane.showMessageDialog(null, 
                "Please login first!", 
                "Unauthorized Access", 
                JOptionPane.WARNING_MESSAGE);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginForm().setVisible(true);
                }
            });
            return;
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDash().setVisible(true);
            }
        });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel generatereceiptpanel2;
    // End of variables declaration//GEN-END:variables
}
