


package LoginandRegister;


import Admin.AdminDash;
import Employee.EmployeeDash;
import Staff.StaffDash;
import config.config;
import javax.swing.JOptionPane;
import Session.Session;
import Session.UserData;

public class LoginForm extends javax.swing.JFrame {

  
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mid = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        donthaveanaccount = new javax.swing.JLabel();
        signin = new javax.swing.JLabel();
        create = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/midname.png"))); // NOI18N
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 290, 370, 200));

        signup.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(51, 51, 255));
        signup.setText("Sign up ");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 10, 310, 120));

        passwordfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)));
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 270, 240, 30));

        email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 240, 30));

        donthaveanaccount.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        donthaveanaccount.setText("Don't Have an Account?");
        getContentPane().add(donthaveanaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        signin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setText("SIGN IN");
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        getContentPane().add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/createbutton.jpg"))); // NOI18N
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 340, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginfunction_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 420, 430));

        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/headername.png"))); // NOI18N
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 470, 350));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -40, 1090, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
      new RegisterForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signupMouseClicked

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
        String userEmail = email.getText().trim();
    String userPassword = new String(passwordfield.getPassword()).trim();

    if (userEmail.isEmpty() || userPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter both email and password!");
        return;
    }

    config conf = new config();
    UserData userData = conf.getUserData(userEmail, userPassword);

    if (userData == null) {
        JOptionPane.showMessageDialog(this, "Invalid email or password!");
        return;
    }

    if (!"Active".equalsIgnoreCase(userData.getStatus())) {
        JOptionPane.showMessageDialog(this, "Account not yet approved.");
        return;
    }

    // SESSION LOGIN
    Session.getInstance().login(
        userData.getId(),
        userData.getUsername(),
        userData.getFirstname(),
        userData.getLastname(),
        userData.getEmail(),
        userData.getType()
    );

    // Welcome message
    String fullName = userData.getFirstname() + " " + userData.getLastname();
    JOptionPane.showMessageDialog(this,
        "Welcome, " + fullName + "!",
        "Login Successful", JOptionPane.INFORMATION_MESSAGE);

    // Redirect to correct dashboard
    switch (userData.getType()) {
        case "Admin":
            new AdminDash(userData.getUsername()).setVisible(true);
            break;
        case "Staff":
            new StaffDash(userData.getUsername()).setVisible(true);
            break;
        case "Employee":
            new EmployeeDash(userData.getUsername()).setVisible(true);
            break;
        default:
            JOptionPane.showMessageDialog(this,
                "Unknown account type: " + userData.getType() + "\nPlease contact the administrator.",
                "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
    }

    this.dispose(); // Close login window once

    }//GEN-LAST:event_signinMouseClicked

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
          signinMouseClicked(null);
    }//GEN-LAST:event_passwordfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // ── FIX: Run database setup FIRST to ensure all columns exist ─────────
        // This adds b_staff, b_address, b_contact etc. to tbl_bookings if missing
        new config().setupDatabase();
 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName())
                .log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel create;
    private javax.swing.JLabel donthaveanaccount;
    private javax.swing.JTextField email;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mid;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel signin;
    private javax.swing.JLabel signup;
    // End of variables declaration//GEN-END:variables
}
