


package Login;

import Admin.AdminDash;
import Register.RegisterForm;
import User.UserDash;
import config.config;
import javax.swing.JOptionPane;
import Session.Session;
import session.UserData;


public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mid = new javax.swing.JLabel();
        signup = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        passwordfield = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        donthaveanaccount = new javax.swing.JLabel();
        signin = new javax.swing.JLabel();
        create = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        head = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/midname.png"))); // NOI18N
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 330, 370, 200));

        signup.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(51, 51, 255));
        signup.setText("Sign up ");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 10, 310, 120));

        passwordfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)));
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 240, 30));

        email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255), new java.awt.Color(51, 51, 255)));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 240, 30));

        donthaveanaccount.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        donthaveanaccount.setText("Don't Have an Account?");
        getContentPane().add(donthaveanaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        signin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        signin.setForeground(new java.awt.Color(255, 255, 255));
        signin.setText("SIGN IN");
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        getContentPane().add(signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/createbutton.jpg"))); // NOI18N
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 340, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginfunction_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 420, 440));

        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/headername.png"))); // NOI18N
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 470, 350));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -40, 1090, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
       RegisterForm rf = new RegisterForm();
       rf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_signupMouseClicked

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
           // Get input values
    String userEmail = email.getText().trim();
    String userPassword = passwordfield.getText().trim();
    
    // Validation
    if (userEmail.isEmpty() || userPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Please enter both email and password!", 
            "Login Error", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get full user data
    config conf = new config();
    UserData userData = conf.getUserData(userEmail, userPassword);
    
    if (userData != null) {
        // CREATE SESSION
        Session session = Session.getInstance();
        session.login(
            userData.getId(),
            userData.getUsername(),
            userData.getFirstname(),
            userData.getLastname(),
            userData.getEmail(),
            userData.getType()
        );
        
        // Debug output
        System.out.println("\n========================================");
        System.out.println("LOGIN SUCCESSFUL!");
        System.out.println("========================================");
        session.printSessionInfo();
        
        // Redirect based on type
        if ("Admin".equalsIgnoreCase(userData.getType())) {
            JOptionPane.showMessageDialog(this, 
                "Welcome " + userData.getFirstname() + " " + userData.getLastname() + "!", 
                "Login Successful", 
                JOptionPane.INFORMATION_MESSAGE);
            AdminDash ad = new AdminDash(userData.getUsername());
            ad.setVisible(true);
            this.dispose();
        } else if ("User".equalsIgnoreCase(userData.getType())) {
            JOptionPane.showMessageDialog(this, 
                "Welcome " + userData.getFirstname() + " " + userData.getLastname() + "!", 
                "Login Successful", 
                JOptionPane.INFORMATION_MESSAGE);
            UserDash ud = new UserDash(userData.getUsername());
            ud.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Unknown user type: " + userData.getType(), 
                "Login Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, 
            "Invalid email or password!", 
            "Login Failed", 
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_signinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel create;
    private javax.swing.JLabel donthaveanaccount;
    private javax.swing.JTextField email;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel mid;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JLabel signin;
    private javax.swing.JLabel signup;
    // End of variables declaration//GEN-END:variables
}
