/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Staff;

import AdminInternalPage.Profile;
import LoginandRegister.LoginForm;
import Session.Session;
import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author ashlaran
 */
public class CreateBooking extends javax.swing.JFrame {

      private config conf = new config();
 
    /**
     * Creates new form CreateBooking
     */
    public CreateBooking() {
        initComponents();
        // ── Clear the hardcoded designer dummy items BEFORE loading real data ──
        serviceslist.removeAllItems();
        assignemployeelist.removeAllItems();
        loadSessionInfo();   // fills username + loads real combo data from DB
    }
 
    // Load logged-in user's name into the sidebar label
    private void loadSessionInfo() {
        Session session = Session.getInstance();
        if (session.isLoggedIn()) {
            lblUsername.setText(session.getUsername());
            loadServicesCombo();
            loadEmployeesCombo();
        } else {
            lblUsername.setText("Staff");
            // Still try to load combos so the form is usable
            loadServicesCombo();
            loadEmployeesCombo();
        }
    }
 
// ── Populate services dropdown from tbl_services (Active only) ─────────────
private void loadServicesCombo() {
    serviceslist.removeAllItems();
    String sql = "SELECT s_name FROM tbl_services WHERE LOWER(s_status) = 'active' ORDER BY s_name ASC";
    try (Connection conn = config.connectDB();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            serviceslist.addItem(rs.getString("s_name"));
        }
    } catch (SQLException e) {
        System.out.println("Error loading services: " + e.getMessage());
    }
    if (serviceslist.getItemCount() == 0) {
        serviceslist.addItem("No services available");
    }
}
 
// ── Populate employees dropdown (Available status only) ────────────────────
private void loadEmployeesCombo() {
    assignemployeelist.removeAllItems();
    String sql = "SELECT (firstname || ' ' || lastname) AS fullname " +
                 "FROM tbl_users WHERE type = 'Employee' AND work_status = 'Available' AND status = 'Active' " +
                 "ORDER BY firstname ASC";
    try (Connection conn = config.connectDB();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            assignemployeelist.addItem(rs.getString("fullname"));
        }
    } catch (SQLException e) {
        System.out.println("Error loading employees: " + e.getMessage());
    }
    if (assignemployeelist.getItemCount() == 0) {
        assignemployeelist.addItem("No available employees");
    }
}
 
// ── Get price of selected service ──────────────────────────────────────────
private double getServicePrice(String serviceName) {
    String sql = "SELECT s_price FROM tbl_services WHERE s_name = ?";
    try (Connection conn = config.connectDB();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setString(1, serviceName);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) return rs.getDouble("s_price");
        }
    } catch (SQLException e) {
        System.out.println("Error getting price: " + e.getMessage());
    }
    return 0.0;
}
 
// ── Get description of selected service ────────────────────────────────────
private String getServiceDescription(String serviceName) {
    String sql = "SELECT s_description FROM tbl_services WHERE s_name = ?";
    try (Connection conn = config.connectDB();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setString(1, serviceName);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                String desc = rs.getString("s_description");
                return desc != null ? desc : "";
            }
        }
    } catch (SQLException e) {
        System.out.println("Error getting description: " + e.getMessage());
    }
    return "";
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // bindingGroup removed — no valid bindings registered

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        panelbottom = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        createbookingheader = new javax.swing.JLabel();
        border1 = new javax.swing.JPanel();
        border2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bookingdetails = new javax.swing.JLabel();
        tasknote = new javax.swing.JLabel();
        tasknotefield = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        contactnumberfield = new javax.swing.JTextField();
        emailaddress = new javax.swing.JLabel();
        fullnamefield = new javax.swing.JTextField();
        assignemployeelist = new javax.swing.JComboBox<>();
        chooseservices = new javax.swing.JLabel();
        emailaddressfield = new javax.swing.JTextField();
        bookingdate = new javax.swing.JLabel();
        bookingdatefield = new javax.swing.JTextField();
        assigncleaner = new javax.swing.JLabel();
        customerdetails = new javax.swing.JLabel();
        statuspanel = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        reminder = new javax.swing.JLabel();
        createpanel = new javax.swing.JPanel();
        create = new javax.swing.JLabel();
        contactnumber = new javax.swing.JLabel();
        serviceslist = new javax.swing.JComboBox<>();
        border3 = new javax.swing.JPanel();
        listadmin = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        availableemployeerpanel = new javax.swing.JPanel();
        availableemployee = new javax.swing.JLabel();
        createbookingpanel3 = new javax.swing.JPanel();
        createbooking3 = new javax.swing.JLabel();
        viewservicespanel = new javax.swing.JPanel();
        viewservices = new javax.swing.JLabel();
        createbookingpanel = new javax.swing.JPanel();
        createbooking = new javax.swing.JLabel();
        servicepanel = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        staff = new javax.swing.JLabel();
        mybookingspanel = new javax.swing.JPanel();
        mybookings = new javax.swing.JLabel();
        createbookingpanel5 = new javax.swing.JPanel();
        createbooking5 = new javax.swing.JLabel();
        feedbackpanel = new javax.swing.JPanel();
        feedback = new javax.swing.JLabel();
        createbookingpanel6 = new javax.swing.JPanel();
        createbooking6 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(28, 69, 91));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbottom.setBackground(new java.awt.Color(29, 45, 61));
        panelbottom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelbottomMouseClicked(evt);
            }
        });
        panelbottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(panelbottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 290));

        jPanel1.setBackground(new java.awt.Color(29, 45, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lg.setForeground(new java.awt.Color(239, 234, 234));
        lg.setText("Log Out");
        jPanel1.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, 20));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (2).png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 30, 20));

        createbookingheader.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        createbookingheader.setForeground(new java.awt.Color(255, 255, 255));
        createbookingheader.setText("Create Booking");
        jPanel1.add(createbookingheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 50));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 660, 50));

        border1.setBackground(new java.awt.Color(29, 45, 61));
        border1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                border1MouseClicked(evt);
            }
        });
        border1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(border1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, 180));

        border2.setBackground(new java.awt.Color(153, 255, 255));
        border2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        border2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                border2MouseClicked(evt);
            }
        });
        border2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(border2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 600, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        // FIX: removed broken ELProperty.create("${}") — crashed on open
        jPanel2.setBackground(new java.awt.Color(28, 69, 91));
        // FIX: bindingGroup.addBinding(binding) removed — binding was null, caused NPE at line 261

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookingdetails.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bookingdetails.setForeground(new java.awt.Color(153, 255, 255));
        bookingdetails.setText("Booking Details");
        jPanel2.add(bookingdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 130, 30));

        tasknote.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        tasknote.setForeground(new java.awt.Color(255, 255, 255));
        tasknote.setText("Task Note (Optional)");
        jPanel2.add(tasknote, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 130, 30));

        tasknotefield.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        tasknotefield.setForeground(new java.awt.Color(102, 102, 102));
        tasknotefield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tasknotefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasknotefieldActionPerformed(evt);
            }
        });
        jPanel2.add(tasknotefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 260, 50));

        address.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Address");
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 30));

        addressfield.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        addressfield.setForeground(new java.awt.Color(102, 102, 102));
        addressfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        addressfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressfieldActionPerformed(evt);
            }
        });
        jPanel2.add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 30));

        contactnumberfield.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        contactnumberfield.setForeground(new java.awt.Color(102, 102, 102));
        contactnumberfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        contactnumberfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnumberfieldActionPerformed(evt);
            }
        });
        jPanel2.add(contactnumberfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 30));

        emailaddress.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        emailaddress.setForeground(new java.awt.Color(255, 255, 255));
        emailaddress.setText("Email Address");
        jPanel2.add(emailaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 30));

        fullnamefield.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        fullnamefield.setForeground(new java.awt.Color(102, 102, 102));
        fullnamefield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fullnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnamefieldActionPerformed(evt);
            }
        });
        jPanel2.add(fullnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 30));

        assignemployeelist.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        assignemployeelist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        assignemployeelist.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        assignemployeelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignemployeelistActionPerformed(evt);
            }
        });
        jPanel2.add(assignemployeelist, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 260, 30));

        chooseservices.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        chooseservices.setForeground(new java.awt.Color(255, 255, 255));
        chooseservices.setText("Choose Services");
        jPanel2.add(chooseservices, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 100, 30));

        emailaddressfield.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        emailaddressfield.setForeground(new java.awt.Color(102, 102, 102));
        emailaddressfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        emailaddressfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailaddressfieldActionPerformed(evt);
            }
        });
        jPanel2.add(emailaddressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 30));

        bookingdate.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bookingdate.setForeground(new java.awt.Color(255, 255, 255));
        bookingdate.setText("Booking Date");
        jPanel2.add(bookingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 100, 30));

        bookingdatefield.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        bookingdatefield.setForeground(new java.awt.Color(102, 102, 102));
        bookingdatefield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bookingdatefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingdatefieldActionPerformed(evt);
            }
        });
        jPanel2.add(bookingdatefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 260, 30));

        assigncleaner.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        assigncleaner.setForeground(new java.awt.Color(255, 255, 255));
        assigncleaner.setText("Assign Cleaner");
        jPanel2.add(assigncleaner, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 100, 30));

        customerdetails.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        customerdetails.setForeground(new java.awt.Color(153, 255, 255));
        customerdetails.setText("Customer Details");
        jPanel2.add(customerdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 30));

        statuspanel.setBackground(new java.awt.Color(0, 153, 0));
        statuspanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        statuspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status.setBackground(new java.awt.Color(153, 255, 255));
        status.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        status.setForeground(new java.awt.Color(153, 255, 255));
        status.setText("Status: Pending");
        statuspanel.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 100, 20));

        jPanel2.add(statuspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 20));

        fullname.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setText("Full Name");
        jPanel2.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        jPanel5.setBackground(new java.awt.Color(28, 69, 100));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reminder.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        reminder.setForeground(new java.awt.Color(255, 255, 255));
        reminder.setText("*All fields are required except Task Note");
        jPanel5.add(reminder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 30));

        createpanel.setBackground(new java.awt.Color(153, 255, 255));
        createpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createpanelMouseClicked(evt);
            }
        });
        createpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        create.setText("Create Booking");
        createpanel.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        jPanel5.add(createpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 130, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 600, 50));

        contactnumber.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        contactnumber.setForeground(new java.awt.Color(255, 255, 255));
        contactnumber.setText("Contact Number");
        jPanel2.add(contactnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 30));

        serviceslist.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        serviceslist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        serviceslist.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        serviceslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceslistActionPerformed(evt);
            }
        });
        jPanel2.add(serviceslist, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 260, 30));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 600, 410));

        border3.setBackground(new java.awt.Color(153, 255, 255));
        border3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                border3MouseClicked(evt);
            }
        });
        border3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(border3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 490));

        listadmin.setBackground(new java.awt.Color(55, 86, 93));
        listadmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        settings.setText("ACCOUNT");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        listadmin.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 10, 290, 50));

        dashpanel.setBackground(new java.awt.Color(29, 45, 61));
        dashpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashpanelMouseExited(evt);
            }
        });
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        dashboard.setForeground(new java.awt.Color(239, 234, 234));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
        });
        dashpanel.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 20));

        listadmin.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 40));

        availableemployeerpanel.setBackground(new java.awt.Color(29, 45, 61));
        availableemployeerpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availableemployeerpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                availableemployeerpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                availableemployeerpanelMouseExited(evt);
            }
        });
        availableemployeerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        availableemployee.setBackground(new java.awt.Color(29, 45, 61));
        availableemployee.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        availableemployee.setForeground(new java.awt.Color(239, 234, 234));
        availableemployee.setText("Av. Employee");
        availableemployeerpanel.add(availableemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        createbookingpanel3.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanel3MouseClicked(evt);
            }
        });
        createbookingpanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking3.setBackground(new java.awt.Color(29, 45, 61));
        createbooking3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking3.setForeground(new java.awt.Color(239, 234, 234));
        createbooking3.setText("Create Booking");
        createbookingpanel3.add(createbooking3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        availableemployeerpanel.add(createbookingpanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        listadmin.add(availableemployeerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 130, 40));

        viewservicespanel.setBackground(new java.awt.Color(29, 45, 61));
        viewservicespanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewservicespanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewservicespanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewservicespanelMouseExited(evt);
            }
        });
        viewservicespanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewservices.setBackground(new java.awt.Color(29, 45, 61));
        viewservices.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        viewservices.setForeground(new java.awt.Color(239, 234, 234));
        viewservices.setText("View Services");
        viewservicespanel.add(viewservices, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        listadmin.add(viewservicespanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 130, 40));

        createbookingpanel.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createbookingpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createbookingpanelMouseExited(evt);
            }
        });
        createbookingpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking.setBackground(new java.awt.Color(29, 45, 61));
        createbooking.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking.setForeground(new java.awt.Color(239, 234, 234));
        createbooking.setText("Create Booking");
        createbookingpanel.add(createbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        listadmin.add(createbookingpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 40));

        servicepanel.setBackground(new java.awt.Color(29, 45, 61));
        servicepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        listadmin.add(servicepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 40));

        lblUsername.setBackground(new java.awt.Color(153, 255, 255));
        lblUsername.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblUsername.setText("Staff");
        listadmin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 70, 20));

        staff.setBackground(new java.awt.Color(153, 255, 255));
        staff.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        staff.setForeground(new java.awt.Color(153, 255, 255));
        staff.setText("Staff");
        listadmin.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 70, 20));

        mybookingspanel.setBackground(new java.awt.Color(29, 45, 61));
        mybookingspanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mybookingspanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mybookingspanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mybookingspanelMouseExited(evt);
            }
        });
        mybookingspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mybookings.setBackground(new java.awt.Color(29, 45, 61));
        mybookings.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        mybookings.setForeground(new java.awt.Color(239, 234, 234));
        mybookings.setText("My Bookings");
        mybookingspanel.add(mybookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        createbookingpanel5.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanel5MouseClicked(evt);
            }
        });
        createbookingpanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking5.setBackground(new java.awt.Color(29, 45, 61));
        createbooking5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking5.setForeground(new java.awt.Color(239, 234, 234));
        createbooking5.setText("Create Booking");
        createbookingpanel5.add(createbooking5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        mybookingspanel.add(createbookingpanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        listadmin.add(mybookingspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 130, 40));

        feedbackpanel.setBackground(new java.awt.Color(29, 45, 61));
        feedbackpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feedbackpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feedbackpanelMouseExited(evt);
            }
        });
        feedbackpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feedback.setBackground(new java.awt.Color(29, 45, 61));
        feedback.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        feedback.setForeground(new java.awt.Color(239, 234, 234));
        feedback.setText("Feedback");
        feedbackpanel.add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, -1));

        createbookingpanel6.setBackground(new java.awt.Color(29, 45, 61));
        createbookingpanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createbookingpanel6MouseClicked(evt);
            }
        });
        createbookingpanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createbooking6.setBackground(new java.awt.Color(29, 45, 61));
        createbooking6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        createbooking6.setForeground(new java.awt.Color(239, 234, 234));
        createbooking6.setText("Create Booking");
        createbookingpanel6.add(createbooking6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        feedbackpanel.add(createbookingpanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 40));

        listadmin.add(feedbackpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 130, 40));

        jPanel4.add(listadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 340));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        // bindingGroup.bind() removed

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
     int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to log out?",
            "Log Out", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Session.getInstance().logout();
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void panelbottomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelbottomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelbottomMouseClicked

    private void contactnumberfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnumberfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnumberfieldActionPerformed

    private void createpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createpanelMouseClicked
        // ── Collect field values ───────────────────────────────────────────────
        String fullName  = fullnamefield.getText().trim();
        String address   = addressfield.getText().trim();
        String contact   = contactnumberfield.getText().trim();
        String emailAddr = emailaddressfield.getText().trim();
        String bookDate  = bookingdatefield.getText().trim();
        String taskNote  = tasknotefield.getText().trim();
        String service   = serviceslist.getSelectedItem() != null
                           ? serviceslist.getSelectedItem().toString() : "";
        String employee  = assignemployeelist.getSelectedItem() != null
                           ? assignemployeelist.getSelectedItem().toString() : "";
        // FIX: store username (not full name) in b_staff for reliable filtering
        String staffUsername = Session.getInstance().getUsername();
        String staffFullName = Session.getInstance().getFullName(); // for receipt display only

        // ── Validation ─────────────────────────────────────────────────────────
        if (fullName.isEmpty() || address.isEmpty() || contact.isEmpty()
                || emailAddr.isEmpty() || bookDate.isEmpty()
                || service.isEmpty() || service.equals("No services available")
                || employee.isEmpty() || employee.equals("No available employees")) {
            JOptionPane.showMessageDialog(this,
                "Please fill in all required fields and ensure\n" +
                "a service and available employee are selected.",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ── Get service price ──────────────────────────────────────────────────
        double price = getServicePrice(service);

        // ── Insert booking into DB ─────────────────────────────────────────────
        String sql = "INSERT INTO tbl_bookings " +
                     "(b_customer, b_address, b_contact, b_email, b_date, " +
                     " b_service, b_employee, b_staff, b_tasknote, b_price, b_status) " +
                     "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'Pending')";
        try (Connection conn = config.connectDB();
             PreparedStatement ps = conn.prepareStatement(sql,
                 java.sql.Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, fullName);
            ps.setString(2, address);
            ps.setString(3, contact);
            ps.setString(4, emailAddr);
            ps.setString(5, bookDate);
            ps.setString(6, service);
            ps.setString(7, employee);
            ps.setString(8, staffUsername); // FIX: username, not full name
            ps.setString(9, taskNote);
            ps.setDouble(10, price);
            ps.executeUpdate();

            // Mark employee Busy
            try (PreparedStatement upd = conn.prepareStatement(
                    "UPDATE tbl_users SET work_status = 'Busy' WHERE " +
                    "(firstname || ' ' || lastname) = ? AND type = 'Employee'")) {
                upd.setString(1, employee);
                upd.executeUpdate();
            }

            // Get the new booking ID for the receipt
            int newBookingId = 0;
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) newBookingId = keys.getInt(1);
            }

            JOptionPane.showMessageDialog(this,
                "Booking created successfully!\nBooking ID: " + newBookingId,
                "Success", JOptionPane.INFORMATION_MESSAGE);

            // Open receipt — when closed, go to MyBookings
            GenerateReceipt receipt = new GenerateReceipt(
                newBookingId, bookDate, fullName, address, contact,
                employee, service, String.valueOf(price), taskNote, staffFullName);
            receipt.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            receipt.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent e) {
                    new MyBookings().setVisible(true);
                }
            });
            receipt.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error creating booking: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createpanelMouseClicked

    private void border1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_border1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_border1MouseClicked

    private void border2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_border2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_border2MouseClicked

    private void tasknotefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasknotefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tasknotefieldActionPerformed

    private void addressfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressfieldActionPerformed

    private void fullnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnamefieldActionPerformed

    private void assignemployeelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignemployeelistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignemployeelistActionPerformed

    private void emailaddressfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailaddressfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailaddressfieldActionPerformed

    private void bookingdatefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingdatefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingdatefieldActionPerformed

    private void serviceslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceslistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceslistActionPerformed

    private void border3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_border3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_border3MouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        new Profile().setVisible(true); this.dispose();
    }//GEN-LAST:event_settingsMouseClicked

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered

    }//GEN-LAST:event_dashboardMouseEntered

    private void dashpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseClicked
        new StaffDash().setVisible(true); this.dispose();
    }//GEN-LAST:event_dashpanelMouseClicked

    private void dashpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseEntered

    }//GEN-LAST:event_dashpanelMouseEntered

    private void dashpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseExited

    }//GEN-LAST:event_dashpanelMouseExited

    private void createbookingpanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanel3MouseClicked

    }//GEN-LAST:event_createbookingpanel3MouseClicked

    private void availableemployeerpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableemployeerpanelMouseClicked
        new AvailableEmployee().setVisible(true); this.dispose();
    }//GEN-LAST:event_availableemployeerpanelMouseClicked

    private void availableemployeerpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableemployeerpanelMouseEntered

    }//GEN-LAST:event_availableemployeerpanelMouseEntered

    private void availableemployeerpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableemployeerpanelMouseExited

    }//GEN-LAST:event_availableemployeerpanelMouseExited

    private void viewservicespanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewservicespanelMouseClicked
        new ViewServices().setVisible(true); this.dispose();
    }//GEN-LAST:event_viewservicespanelMouseClicked

    private void viewservicespanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewservicespanelMouseEntered

    }//GEN-LAST:event_viewservicespanelMouseEntered

    private void viewservicespanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewservicespanelMouseExited

    }//GEN-LAST:event_viewservicespanelMouseExited

    private void createbookingpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanelMouseClicked
        new CreateBooking().setVisible(true); this.dispose();
    }//GEN-LAST:event_createbookingpanelMouseClicked

    private void createbookingpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanelMouseEntered

    }//GEN-LAST:event_createbookingpanelMouseEntered

    private void createbookingpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanelMouseExited

    }//GEN-LAST:event_createbookingpanelMouseExited

    private void createbookingpanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanel5MouseClicked

    }//GEN-LAST:event_createbookingpanel5MouseClicked

    private void mybookingspanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mybookingspanelMouseClicked
        new MyBookings().setVisible(true); this.dispose();
    }//GEN-LAST:event_mybookingspanelMouseClicked

    private void mybookingspanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mybookingspanelMouseEntered

    }//GEN-LAST:event_mybookingspanelMouseEntered

    private void mybookingspanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mybookingspanelMouseExited

    }//GEN-LAST:event_mybookingspanelMouseExited

    private void createbookingpanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createbookingpanel6MouseClicked

    }//GEN-LAST:event_createbookingpanel6MouseClicked

    private void feedbackpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackpanelMouseClicked
        new Feedback().setVisible(true); this.dispose();
    }//GEN-LAST:event_feedbackpanelMouseClicked

    private void feedbackpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackpanelMouseEntered

    }//GEN-LAST:event_feedbackpanelMouseEntered

    private void feedbackpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackpanelMouseExited

    }//GEN-LAST:event_feedbackpanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            Session session = Session.getInstance();
        if (!session.isLoggedIn()) {
            JOptionPane.showMessageDialog(null, 
                "Please login first!", 
                "Unauthorized Access", 
                JOptionPane.WARNING_MESSAGE);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginForm().setVisible(true);
                }
            });
            return;
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffDash().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressfield;
    private javax.swing.JLabel assigncleaner;
    private javax.swing.JComboBox<String> assignemployeelist;
    private javax.swing.JLabel availableemployee;
    private javax.swing.JPanel availableemployeerpanel;
    private javax.swing.JLabel bookingdate;
    private javax.swing.JTextField bookingdatefield;
    private javax.swing.JLabel bookingdetails;
    private javax.swing.JPanel border1;
    private javax.swing.JPanel border2;
    private javax.swing.JPanel border3;
    private javax.swing.JLabel chooseservices;
    private javax.swing.JLabel contactnumber;
    private javax.swing.JTextField contactnumberfield;
    private javax.swing.JLabel create;
    private javax.swing.JLabel createbooking;
    private javax.swing.JLabel createbooking3;
    private javax.swing.JLabel createbooking5;
    private javax.swing.JLabel createbooking6;
    private javax.swing.JLabel createbookingheader;
    private javax.swing.JPanel createbookingpanel;
    private javax.swing.JPanel createbookingpanel3;
    private javax.swing.JPanel createbookingpanel5;
    private javax.swing.JPanel createbookingpanel6;
    private javax.swing.JPanel createpanel;
    private javax.swing.JLabel customerdetails;
    private javax.swing.JLabel dashboard;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JLabel emailaddress;
    private javax.swing.JTextField emailaddressfield;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel feedback;
    private javax.swing.JPanel feedbackpanel;
    private javax.swing.JLabel fullname;
    private javax.swing.JTextField fullnamefield;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lg;
    private javax.swing.JPanel listadmin;
    private javax.swing.JLabel mybookings;
    private javax.swing.JPanel mybookingspanel;
    private javax.swing.JPanel panelbottom;
    private javax.swing.JLabel reminder;
    private javax.swing.JPanel servicepanel;
    private javax.swing.JComboBox<String> serviceslist;
    private javax.swing.JLabel settings;
    private javax.swing.JLabel staff;
    private javax.swing.JLabel status;
    private javax.swing.JPanel statuspanel;
    private javax.swing.JLabel tasknote;
    private javax.swing.JTextField tasknotefield;
    private javax.swing.JLabel viewservices;
    private javax.swing.JPanel viewservicespanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

   
}
