/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Login.LoginForm;

/**
 *
 * @author ashlaran
 */
public class AdminDash extends javax.swing.JFrame {
    
  private String loggedInUsername;
    /**
     * Creates new form AdminDash
     */
    public AdminDash() {
        initComponents();
         this.loggedInUsername = "Admin"; // Default
    }

    /**
     * Constructor with username parameter
     */
    public AdminDash(String username) {
        initComponents();
        this.loggedInUsername = username;
        lblUsername.setText("Welcome, " + username + "!"); // Display username
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listadmin = new javax.swing.JPanel();
        exitpanel1 = new javax.swing.JPanel();
        LOGOUT = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        dashboard1 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        bookingpanel = new javax.swing.JPanel();
        booking = new javax.swing.JLabel();
        servicepanel = new javax.swing.JPanel();
        service = new javax.swing.JLabel();
        paymentpanel = new javax.swing.JPanel();
        payment = new javax.swing.JLabel();
        staffpanel = new javax.swing.JPanel();
        staff = new javax.swing.JLabel();
        exitpanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        reviewpanel = new javax.swing.JPanel();
        review = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listadmin.setBackground(new java.awt.Color(204, 204, 204));
        listadmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitpanel1MouseClicked(evt);
            }
        });
        exitpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGOUT.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LOGOUT.setText("LOGOUT");
        exitpanel1.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 20));

        listadmin.add(exitpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 170, 40));

        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        dashboard1.setText("DASHBOARD");
        dashpanel.add(dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 20));

        listadmin.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 40));

        userpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpanelMouseClicked(evt);
            }
        });
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        user.setText("USERS");
        userpanel.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, -1));

        listadmin.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 40));

        bookingpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booking.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        booking.setText("BOOKINGS");
        bookingpanel.add(booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        listadmin.add(bookingpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 40));

        servicepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        service.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        service.setText("SERVICES");
        servicepanel.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        listadmin.add(servicepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        paymentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payment.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        payment.setText("PAYMENTS");
        paymentpanel.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        listadmin.add(paymentpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 40));

        staffpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staff.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        staff.setText("STAFF");
        staffpanel.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, -1));

        listadmin.add(staffpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 40));

        exitpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        exit.setText("MONITOR");
        exitpanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        listadmin.add(exitpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 170, 40));

        reviewpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        review.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        review.setText("REVIEWS ");
        reviewpanel.add(review, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));

        listadmin.add(reviewpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 170, 40));

        lblUsername.setText("WELCOME, ADMIN!");
        listadmin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        getContentPane().add(listadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 490));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseClicked
     Listofusers u = new Listofusers(loggedInUsername); // ← PASS USERNAME
   u.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_userpanelMouseClicked

    private void exitpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitpanel1MouseClicked
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitpanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel booking;
    private javax.swing.JPanel bookingpanel;
    private javax.swing.JLabel dashboard1;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JPanel exitpanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel listadmin;
    private javax.swing.JLabel payment;
    private javax.swing.JPanel paymentpanel;
    private javax.swing.JLabel review;
    private javax.swing.JPanel reviewpanel;
    private javax.swing.JLabel service;
    private javax.swing.JPanel servicepanel;
    private javax.swing.JLabel staff;
    private javax.swing.JPanel staffpanel;
    private javax.swing.JLabel user;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
