/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import AdminInternalPage.Profile;
import LoginandRegister.LoginForm;
import Session.Session;
import javax.swing.JOptionPane;
import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author ashlaran
 */
public class AdminDash extends javax.swing.JFrame {

    
      public AdminDash(String username) {
    initComponents();
    lblUsername.setText(username);
    setupReportComboBox(); // FIX: initialize combobox before loading data
    loadDashboardData();
}
   
   public AdminDash() {
    initComponents();
    setupReportComboBox(); // FIX: initialize combobox before loading data
    loadDashboardData();
    Session session = Session.getInstance();
    lblUsername.setText(session.getUsername());
}
 
   // FIX: Properly initialize the Report Type ComboBox with filter options
   private void setupReportComboBox() {
       reporttypecombobox.removeAllItems();
       reporttypecombobox.addItem("All");
       reporttypecombobox.addItem("Pending");
       reporttypecombobox.addItem("In Progress");
       reporttypecombobox.addItem("Done");
       reporttypecombobox.addItem("Cancelled");
   }
   
   private void loadDashboardData() {
 
    config conf = new config();
 
    try (Connection conn = config.connectDB()) {
 
        PreparedStatement ps1 = conn.prepareStatement("SELECT COUNT(*) FROM tbl_users");
        ResultSet rs1 = ps1.executeQuery();
        if (rs1.next()) totalusersnum.setText(rs1.getString(1));
 
        PreparedStatement ps2 = conn.prepareStatement("SELECT COUNT(*) FROM tbl_users WHERE type='Employee'");
        ResultSet rs2 = ps2.executeQuery();
        if (rs2.next()) totalemployeesnum.setText(rs2.getString(1));
 
        PreparedStatement ps3 = conn.prepareStatement("SELECT COUNT(*) FROM tbl_bookings");
        ResultSet rs3 = ps3.executeQuery();
        if (rs3.next()) totalbookingsnum.setText(rs3.getString(1));
 
        PreparedStatement ps4 = conn.prepareStatement("SELECT COUNT(*) FROM tbl_bookings WHERE b_status='Pending'");
        ResultSet rs4 = ps4.executeQuery();
        if (rs4.next()) totalpendingnum.setText(rs4.getString(1));
 
        PreparedStatement ps5 = conn.prepareStatement("SELECT COUNT(*) FROM tbl_services");
        ResultSet rs5 = ps5.executeQuery();
        if (rs5.next()) totalservicesnum.setText(rs5.getString(1));
 
        conf.displayData(
            "SELECT b_id AS ID, b_customer AS Customer, b_service AS Service, b_date AS Date, b_status AS Status " +
            "FROM tbl_bookings ORDER BY b_id DESC LIMIT 20",
            TableRecentBookings
        );
 
        conf.displayData(
            "SELECT firstname || ' ' || lastname AS Name, work_status AS 'Work Status' " +
            "FROM tbl_users WHERE type='Employee'",
            TableEmployeeStatus
        );
 
    } catch (Exception e) {
        e.printStackTrace();
    }
 
}
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        admindashboard = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        totalemployeespanel = new javax.swing.JPanel();
        totalbookingsborder4 = new javax.swing.JPanel();
        skyblue = new javax.swing.JPanel();
        totalemployeesnum = new javax.swing.JLabel();
        totalemployees = new javax.swing.JLabel();
        totalbookingspanel = new javax.swing.JPanel();
        totalbookingsborder3 = new javax.swing.JPanel();
        green = new javax.swing.JPanel();
        totalbookingsnum = new javax.swing.JLabel();
        totalbookings = new javax.swing.JLabel();
        totalpendingpanel = new javax.swing.JPanel();
        totalbookingsborder2 = new javax.swing.JPanel();
        yellow = new javax.swing.JPanel();
        totalpendingnum = new javax.swing.JLabel();
        totalpending = new javax.swing.JLabel();
        totalservicespanel = new javax.swing.JPanel();
        totalbookingsborder1 = new javax.swing.JPanel();
        red = new javax.swing.JPanel();
        totalservicesnum = new javax.swing.JLabel();
        totalservices = new javax.swing.JLabel();
        totaluserspanel = new javax.swing.JPanel();
        totalbookingsborder = new javax.swing.JPanel();
        blue = new javax.swing.JPanel();
        totalusersnum = new javax.swing.JLabel();
        totalusers = new javax.swing.JLabel();
        employeestatus = new javax.swing.JLabel();
        recentbookingscrollpane = new javax.swing.JScrollPane();
        TableRecentBookings = new javax.swing.JTable();
        employeestatusscrollpane = new javax.swing.JScrollPane();
        TableEmployeeStatus = new javax.swing.JTable();
        recentbookings = new javax.swing.JLabel();
        border2 = new javax.swing.JPanel();
        border3 = new javax.swing.JPanel();
        reporttypecombobox = new javax.swing.JComboBox<>();
        listadmin = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        dashboard1 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        users = new javax.swing.JLabel();
        employeepanel = new javax.swing.JPanel();
        employee = new javax.swing.JLabel();
        servicespanel = new javax.swing.JPanel();
        services = new javax.swing.JLabel();
        bookingspanel = new javax.swing.JPanel();
        bookings = new javax.swing.JLabel();
        reportspanel = new javax.swing.JPanel();
        reports = new javax.swing.JLabel();
        feedbackpanel = new javax.swing.JPanel();
        review = new javax.swing.JLabel();
        feedback = new javax.swing.JLabel();
        administrator = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(28, 69, 91));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 45, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lg.setForeground(new java.awt.Color(239, 234, 234));
        lg.setText("Log Out");
        jPanel1.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 20));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (2).png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 20));

        admindashboard.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        admindashboard.setForeground(new java.awt.Color(239, 234, 234));
        admindashboard.setText("Admin Dashboard");
        jPanel1.add(admindashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 50));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 50));

        jPanel2.setBackground(new java.awt.Color(29, 45, 61));
        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 150, 140));

        totalemployeespanel.setBackground(new java.awt.Color(29, 45, 61));
        totalemployeespanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        totalemployeespanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalbookingsborder4.setBackground(new java.awt.Color(153, 255, 255));
        totalbookingsborder4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        totalemployeespanel.add(totalbookingsborder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 90));

        skyblue.setBackground(new java.awt.Color(153, 255, 255));
        skyblue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totalemployeespanel.add(skyblue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 40));

        totalemployeesnum.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        totalemployeesnum.setForeground(new java.awt.Color(255, 255, 255));
        totalemployeesnum.setText("0");
        totalemployeespanel.add(totalemployeesnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        totalemployees.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        totalemployees.setForeground(new java.awt.Color(255, 255, 255));
        totalemployees.setText("Employees");
        totalemployeespanel.add(totalemployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        jPanel4.add(totalemployeespanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, 80));

        totalbookingspanel.setBackground(new java.awt.Color(29, 45, 61));
        totalbookingspanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        totalbookingspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalbookingsborder3.setBackground(new java.awt.Color(0, 255, 153));
        totalbookingsborder3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        totalbookingspanel.add(totalbookingsborder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 90));

        green.setBackground(new java.awt.Color(0, 255, 153));
        green.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totalbookingspanel.add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 40));

        totalbookingsnum.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        totalbookingsnum.setForeground(new java.awt.Color(255, 255, 255));
        totalbookingsnum.setText("0");
        totalbookingspanel.add(totalbookingsnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        totalbookings.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        totalbookings.setForeground(new java.awt.Color(255, 255, 255));
        totalbookings.setText("Total Bookings");
        totalbookingspanel.add(totalbookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        jPanel4.add(totalbookingspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 120, 80));

        totalpendingpanel.setBackground(new java.awt.Color(29, 45, 61));
        totalpendingpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        totalpendingpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalbookingsborder2.setBackground(new java.awt.Color(255, 255, 51));
        totalbookingsborder2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        totalpendingpanel.add(totalbookingsborder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 90));

        yellow.setBackground(new java.awt.Color(255, 255, 51));
        yellow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totalpendingpanel.add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 40));

        totalpendingnum.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        totalpendingnum.setForeground(new java.awt.Color(255, 255, 255));
        totalpendingnum.setText("0");
        totalpendingpanel.add(totalpendingnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, -1));

        totalpending.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        totalpending.setForeground(new java.awt.Color(255, 255, 255));
        totalpending.setText("Pending");
        totalpendingpanel.add(totalpending, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        jPanel4.add(totalpendingpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 120, 80));

        totalservicespanel.setBackground(new java.awt.Color(29, 45, 61));
        totalservicespanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        totalservicespanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalbookingsborder1.setBackground(new java.awt.Color(255, 51, 51));
        totalbookingsborder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        totalservicespanel.add(totalbookingsborder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 90));

        red.setBackground(new java.awt.Color(255, 51, 51));
        red.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totalservicespanel.add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 40));

        totalservicesnum.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        totalservicesnum.setForeground(new java.awt.Color(255, 255, 255));
        totalservicesnum.setText("0");
        totalservicespanel.add(totalservicesnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 20, -1));

        totalservices.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        totalservices.setForeground(new java.awt.Color(255, 255, 255));
        totalservices.setText("Services");
        totalservicespanel.add(totalservices, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        jPanel4.add(totalservicespanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 120, 80));

        totaluserspanel.setBackground(new java.awt.Color(29, 45, 61));
        totaluserspanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        totaluserspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalbookingsborder.setBackground(new java.awt.Color(0, 102, 255));
        totalbookingsborder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        totaluserspanel.add(totalbookingsborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 90));

        blue.setBackground(new java.awt.Color(0, 102, 255));
        blue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totaluserspanel.add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 40));

        totalusersnum.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        totalusersnum.setForeground(new java.awt.Color(255, 255, 255));
        totalusersnum.setText("0");
        totaluserspanel.add(totalusersnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        totalusers.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        totalusers.setForeground(new java.awt.Color(255, 255, 255));
        totalusers.setText("Total Users");
        totaluserspanel.add(totalusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        jPanel4.add(totaluserspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, 80));

        employeestatus.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        employeestatus.setForeground(new java.awt.Color(255, 255, 255));
        employeestatus.setText("Employee Status");
        jPanel4.add(employeestatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 110, 30));

        recentbookingscrollpane.setBackground(new java.awt.Color(29, 45, 61));
        recentbookingscrollpane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        recentbookingscrollpane.setForeground(new java.awt.Color(255, 255, 255));
        recentbookingscrollpane.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N

        TableRecentBookings.setBackground(new java.awt.Color(29, 45, 61));
        TableRecentBookings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableRecentBookings.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        TableRecentBookings.setForeground(new java.awt.Color(255, 255, 255));
        TableRecentBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Customer", "Service", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableRecentBookings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        recentbookingscrollpane.setViewportView(TableRecentBookings);

        jPanel4.add(recentbookingscrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 340, 290));

        employeestatusscrollpane.setBackground(new java.awt.Color(29, 45, 61));
        employeestatusscrollpane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        employeestatusscrollpane.setForeground(new java.awt.Color(255, 255, 255));
        employeestatusscrollpane.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N

        TableEmployeeStatus.setBackground(new java.awt.Color(29, 45, 61));
        TableEmployeeStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableEmployeeStatus.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        TableEmployeeStatus.setForeground(new java.awt.Color(255, 255, 255));
        TableEmployeeStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Work Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableEmployeeStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeestatusscrollpane.setViewportView(TableEmployeeStatus);

        jPanel4.add(employeestatusscrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 260, 290));

        recentbookings.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        recentbookings.setForeground(new java.awt.Color(255, 255, 255));
        recentbookings.setText("Recent Bookings");
        jPanel4.add(recentbookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 110, 30));

        border2.setBackground(new java.awt.Color(153, 255, 255));
        border2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        border2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                border2MouseClicked(evt);
            }
        });
        border2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(border2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 630, 10));

        border3.setBackground(new java.awt.Color(153, 255, 255));
        border3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                border3MouseClicked(evt);
            }
        });
        border3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(border3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 490));

        reporttypecombobox.setBackground(new java.awt.Color(29, 45, 61));
        reporttypecombobox.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        reporttypecombobox.setForeground(new java.awt.Color(29, 45, 61));
        reporttypecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Pending", "In Progress", "Done", "Cancelled" }));
        reporttypecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporttypecomboboxActionPerformed(evt);
            }
        });
        jPanel4.add(reporttypecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 100, -1));

        listadmin.setBackground(new java.awt.Color(55, 86, 93));
        listadmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        settings.setText("ACCOUNT");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        listadmin.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 10, 280, 50));

        lblUsername.setBackground(new java.awt.Color(153, 255, 255));
        lblUsername.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblUsername.setText("Admin");
        listadmin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 20));

        dashpanel.setBackground(new java.awt.Color(29, 45, 61));
        dashpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpanelMouseClicked(evt);
            }
        });
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        dashboard1.setForeground(new java.awt.Color(239, 234, 234));
        dashboard1.setText("Dashboard");
        dashpanel.add(dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        listadmin.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 40));

        userpanel.setBackground(new java.awt.Color(29, 45, 61));
        userpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpanelMouseClicked(evt);
            }
        });
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        users.setBackground(new java.awt.Color(29, 45, 61));
        users.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        users.setForeground(new java.awt.Color(239, 234, 234));
        users.setText("Users");
        userpanel.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, -1));

        listadmin.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 150, 40));

        employeepanel.setBackground(new java.awt.Color(29, 45, 61));
        employeepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeepanelMouseClicked(evt);
            }
        });
        employeepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employee.setBackground(new java.awt.Color(212, 226, 240));
        employee.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        employee.setForeground(new java.awt.Color(239, 234, 234));
        employee.setText("Employee");
        employeepanel.add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        listadmin.add(employeepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 40));

        servicespanel.setBackground(new java.awt.Color(29, 45, 61));
        servicespanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicespanelMouseClicked(evt);
            }
        });
        servicespanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        services.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        services.setForeground(new java.awt.Color(239, 234, 234));
        services.setText("Services");
        servicespanel.add(services, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, -1));

        listadmin.add(servicespanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 40));

        bookingspanel.setBackground(new java.awt.Color(29, 45, 61));
        bookingspanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingspanelMouseClicked(evt);
            }
        });
        bookingspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookings.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        bookings.setForeground(new java.awt.Color(239, 234, 234));
        bookings.setText("Bookings");
        bookingspanel.add(bookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        listadmin.add(bookingspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 150, 40));

        reportspanel.setBackground(new java.awt.Color(29, 45, 61));
        reportspanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportspanelMouseClicked(evt);
            }
        });
        reportspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reports.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        reports.setForeground(new java.awt.Color(239, 234, 234));
        reports.setText("Reports");
        reportspanel.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        listadmin.add(reportspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 150, 40));

        feedbackpanel.setBackground(new java.awt.Color(29, 45, 61));
        feedbackpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackpanelMouseClicked(evt);
            }
        });
        feedbackpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        review.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        feedbackpanel.add(review, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));

        feedback.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        feedback.setForeground(new java.awt.Color(239, 234, 234));
        feedback.setText("Feedback");
        feedbackpanel.add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, -1));

        listadmin.add(feedbackpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 150, 40));

        administrator.setBackground(new java.awt.Color(153, 255, 255));
        administrator.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        administrator.setForeground(new java.awt.Color(153, 255, 255));
        administrator.setText("ADMINISTRATOR");
        listadmin.add(administrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, 20));

        jPanel4.add(listadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
         int c = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) {
            Session.getInstance().logout();
            new LoginForm().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void border2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_border2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_border2MouseClicked

    private void border3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_border3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_border3MouseClicked

    private void reporttypecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporttypecomboboxActionPerformed
         filterRecentBookings();
    }//GEN-LAST:event_reporttypecomboboxActionPerformed

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        Profile p = new Profile();
        p.SetVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsMouseClicked

    private void dashpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseClicked
      AdminDash a = new AdminDash();
      a.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_dashpanelMouseClicked

    private void userpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseClicked
        Users u = new Users();
      u.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_userpanelMouseClicked

    private void employeepanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeepanelMouseClicked
        Employee e = new Employee();
      e.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_employeepanelMouseClicked

    private void servicespanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicespanelMouseClicked
        Services s  = new Services();
      s.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_servicespanelMouseClicked

    private void bookingspanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingspanelMouseClicked
        Bookings b = new Bookings();
      b.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_bookingspanelMouseClicked

    private void reportspanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportspanelMouseClicked
        Reports r = new Reports();
      r.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_reportspanelMouseClicked

    private void feedbackpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackpanelMouseClicked
         Feedback f = new Feedback();
      f.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_feedbackpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Session session = Session.getInstance();
        if (!session.isLoggedIn()) {
            JOptionPane.showMessageDialog(null, "Please login first!", "Unauthorized Access", JOptionPane.WARNING_MESSAGE);
            java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true)); return;
        }
        java.awt.EventQueue.invokeLater(() -> new AdminDash().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableEmployeeStatus;
    private javax.swing.JTable TableRecentBookings;
    private javax.swing.JLabel admindashboard;
    private javax.swing.JLabel administrator;
    private javax.swing.JPanel blue;
    private javax.swing.JLabel bookings;
    private javax.swing.JPanel bookingspanel;
    private javax.swing.JPanel border2;
    private javax.swing.JPanel border3;
    private javax.swing.JLabel dashboard1;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JLabel employee;
    private javax.swing.JPanel employeepanel;
    private javax.swing.JLabel employeestatus;
    private javax.swing.JScrollPane employeestatusscrollpane;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel feedback;
    private javax.swing.JPanel feedbackpanel;
    private javax.swing.JPanel green;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lg;
    private javax.swing.JPanel listadmin;
    private javax.swing.JLabel recentbookings;
    private javax.swing.JScrollPane recentbookingscrollpane;
    private javax.swing.JPanel red;
    private javax.swing.JLabel reports;
    private javax.swing.JPanel reportspanel;
    private javax.swing.JComboBox<String> reporttypecombobox;
    private javax.swing.JLabel review;
    private javax.swing.JLabel services;
    private javax.swing.JPanel servicespanel;
    private javax.swing.JLabel settings;
    private javax.swing.JPanel skyblue;
    private javax.swing.JLabel totalbookings;
    private javax.swing.JPanel totalbookingsborder;
    private javax.swing.JPanel totalbookingsborder1;
    private javax.swing.JPanel totalbookingsborder2;
    private javax.swing.JPanel totalbookingsborder3;
    private javax.swing.JPanel totalbookingsborder4;
    private javax.swing.JLabel totalbookingsnum;
    private javax.swing.JPanel totalbookingspanel;
    private javax.swing.JLabel totalemployees;
    private javax.swing.JLabel totalemployeesnum;
    private javax.swing.JPanel totalemployeespanel;
    private javax.swing.JLabel totalpending;
    private javax.swing.JLabel totalpendingnum;
    private javax.swing.JPanel totalpendingpanel;
    private javax.swing.JLabel totalservices;
    private javax.swing.JLabel totalservicesnum;
    private javax.swing.JPanel totalservicespanel;
    private javax.swing.JLabel totalusers;
    private javax.swing.JLabel totalusersnum;
    private javax.swing.JPanel totaluserspanel;
    private javax.swing.JPanel userpanel;
    private javax.swing.JLabel users;
    private javax.swing.JPanel yellow;
    // End of variables declaration//GEN-END:variables

    private void filterRecentBookings() {
        String selected = (String) reporttypecombobox.getSelectedItem();
        config conf = new config();
 
        String sql;
        if (selected == null || selected.equals("All")) {
            sql = "SELECT b_id AS ID, b_customer AS Customer, b_service AS Service, " +
                  "b_date AS Date, b_status AS Status " +
                  "FROM tbl_bookings ORDER BY b_id DESC LIMIT 20";
        } else {
            sql = "SELECT b_id AS ID, b_customer AS Customer, b_service AS Service, " +
                  "b_date AS Date, b_status AS Status " +
                  "FROM tbl_bookings WHERE b_status='" + selected + "' ORDER BY b_id DESC LIMIT 20";
        }
 
        conf.displayData(sql, TableRecentBookings);
    }
 
  
  
}
