/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Login.LoginForm;
import config.config;
import javax.swing.JOptionPane;
import Session.Session;

/**
 *
 * @author ashlaran
 */
public class Listofusers extends javax.swing.JFrame {
    
    
    

    private String loggedInUsername;

    /**
     * Creates new form Users
     */
   public Listofusers() {
    initComponents();
    loadUserData();

    // 🔐 Get session info
    Session session = Session.getInstance();
    String currentUser = session.getFullName();
    String email = session.getEmail();
    boolean isAdmin = session.isAdmin();

    // 👤 Show logged-in user
    lblUsername.setText("Welcome, " + currentUser + "!");

    // 🔒 Optional: restrict access
    if (!isAdmin) {
        JOptionPane.showMessageDialog(this,
            "Access denied. Admins only.",
            "Unauthorized",
            JOptionPane.ERROR_MESSAGE);
        System.exit(0);
    }
}
    
    
    /**
 * Constructor with username parameter
 */
 /**
     * Constructor with username parameter
     */
    public Listofusers(String username) {
        initComponents();
        loadUserData();
        this.loggedInUsername = username;
        lblUsername.setText("Welcome, " + username + "!"); // Display username
    }
    
private void loadUserData() {
    config dbConfig = new config();
    String sql = "SELECT u_id, firstname, lastname, username, email, password, type FROM tbl_users";
    dbConfig.displayData(sql, jTable1);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listadmin = new javax.swing.JPanel();
        exitpanel1 = new javax.swing.JPanel();
        LOGOUT = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        dashboard1 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        bookingpanel = new javax.swing.JPanel();
        booking = new javax.swing.JLabel();
        servicepanel = new javax.swing.JPanel();
        service = new javax.swing.JLabel();
        paymentpanel = new javax.swing.JPanel();
        payment = new javax.swing.JLabel();
        staffpanel = new javax.swing.JPanel();
        staff = new javax.swing.JLabel();
        exitpanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        reviewpanel = new javax.swing.JPanel();
        review = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listadmin.setBackground(new java.awt.Color(204, 204, 204));
        listadmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitpanel1MouseClicked(evt);
            }
        });
        exitpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGOUT.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        LOGOUT.setText("LOGOUT");
        exitpanel1.add(LOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 80, 20));

        listadmin.add(exitpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 170, 40));

        dashpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashpanelMouseClicked(evt);
            }
        });
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        dashboard1.setText("DASHBOARD");
        dashpanel.add(dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 20));

        listadmin.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 40));

        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        user.setText("USERS");
        userpanel.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, -1));

        listadmin.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, 40));

        bookingpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booking.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        booking.setText("BOOKINGS");
        bookingpanel.add(booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        listadmin.add(bookingpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 40));

        servicepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        service.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        service.setText("SERVICES");
        servicepanel.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        listadmin.add(servicepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 40));

        paymentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payment.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        payment.setText("PAYMENTS");
        paymentpanel.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, -1));

        listadmin.add(paymentpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 40));

        staffpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staff.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        staff.setText("STAFF");
        staffpanel.add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, -1));

        listadmin.add(staffpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 170, 40));

        exitpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        exit.setText("MONITOR");
        exitpanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 100, -1));

        listadmin.add(exitpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 170, 40));

        reviewpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        review.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        review.setText("REVIEWS ");
        reviewpanel.add(review, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));

        listadmin.add(reviewpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 170, 40));

        lblUsername.setText("WELCOME, ADMIN!");
        listadmin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(listadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 490));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "u_id", "First Name", "Last Name", "User Name", "Email", "Password", "type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 620, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashpanelMouseClicked
       AdminDash ad = new AdminDash(loggedInUsername); // ← PASS USERNAME BACK
    ad.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_dashpanelMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    
    // Get selected row
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Please select a user to delete!", 
            "No Selection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get user details
    int userId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
    String username = jTable1.getValueAt(selectedRow, 3).toString();
    
    // Confirm deletion
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete user '" + username + "'?\n\nThis action cannot be undone!", 
        "Confirm Deletion", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Delete from database
        config dbConfig = new config();
        String sql = "DELETE FROM tbl_users WHERE u_id=?";
        dbConfig.deleteRecord(sql, userId);
        
        JOptionPane.showMessageDialog(this, 
            "User deleted successfully!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Refresh table
        loadUserData();
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         // Get selected row
    // Get selected row
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Please select a user to edit!", 
            "No Selection", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get current values from selected row
    int userId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
    String currentFirstname = jTable1.getValueAt(selectedRow, 1).toString();
    String currentLastname = jTable1.getValueAt(selectedRow, 2).toString();
    String currentUsername = jTable1.getValueAt(selectedRow, 3).toString();
    String currentEmail = jTable1.getValueAt(selectedRow, 4).toString();
    String currentPassword = jTable1.getValueAt(selectedRow, 5).toString();
    String currentType = jTable1.getValueAt(selectedRow, 6).toString();
    
    // Create input dialogs for editing
    String firstname = JOptionPane.showInputDialog(this, "First Name:", currentFirstname);
    if (firstname == null) return; // User cancelled
    
    String lastname = JOptionPane.showInputDialog(this, "Last Name:", currentLastname);
    if (lastname == null) return;
    
    String username = JOptionPane.showInputDialog(this, "Username:", currentUsername);
    if (username == null) return;
    
    String email = JOptionPane.showInputDialog(this, "Email:", currentEmail);
    if (email == null) return;
    
    String password = JOptionPane.showInputDialog(this, "Password:", currentPassword);
    if (password == null) return;
    
    // Dropdown for user type
    String[] types = {"User", "Admin"};
    String type = (String) JOptionPane.showInputDialog(
        this,
        "Select User Type:",
        "User Type",
        JOptionPane.QUESTION_MESSAGE,
        null,
        types,
        currentType
    );
    if (type == null) return;
    
    // Validate inputs
    if (firstname.trim().isEmpty() || lastname.trim().isEmpty() || 
        username.trim().isEmpty() || email.trim().isEmpty() || password.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "All fields are required!", 
            "Validation Error", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Update in database
    config dbConfig = new config();
    String sql = "UPDATE tbl_users SET firstname=?, lastname=?, username=?, email=?, password=?, type=? WHERE u_id=?";
    dbConfig.updateRecord(sql, firstname, lastname, username, email, password, type, userId);
    
    JOptionPane.showMessageDialog(this, 
        "User updated successfully!", 
        "Success", 
        JOptionPane.INFORMATION_MESSAGE);
    
    // Refresh table
    loadUserData();

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    
    loadUserData();
    JOptionPane.showMessageDialog(this, 
        "User list refreshed!", 
        "Refreshed", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void exitpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitpanel1MouseClicked
       LoginForm lf = new LoginForm();
       lf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_exitpanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listofusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listofusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listofusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listofusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listofusers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGOUT;
    private javax.swing.JLabel booking;
    private javax.swing.JPanel bookingpanel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel dashboard1;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JPanel exitpanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel listadmin;
    private javax.swing.JLabel payment;
    private javax.swing.JPanel paymentpanel;
    private javax.swing.JLabel review;
    private javax.swing.JPanel reviewpanel;
    private javax.swing.JLabel service;
    private javax.swing.JPanel servicepanel;
    private javax.swing.JLabel staff;
    private javax.swing.JPanel staffpanel;
    private javax.swing.JLabel user;
    private javax.swing.JPanel userpanel;
    // End of variables declaration//GEN-END:variables
}
