/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;


import AdminInternalPage.Profile;
import AdminInternalPage.ServiceForm;
import LoginandRegister.LoginForm;
import Session.Session;
import config.config;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
public class Services extends javax.swing.JFrame {

   
   
   
    private final config conf = new config();

    public Services() {
        initComponents();
        loadSessionInfo();
        loadTable("");
    }


 // ── Show logged-in admin name in the sidebar label ───────────────────────
    private void loadSessionInfo() {
        Session session = Session.getInstance();
        if (session.isLoggedIn()) {
            lblUsername.setText(session.getFullName());
        } else {
            lblUsername.setText("ADMIN");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        admindashboard = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addpanel = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        editpanel = new javax.swing.JPanel();
        edit = new javax.swing.JLabel();
        deletepanel = new javax.swing.JPanel();
        delete = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        search = new javax.swing.JLabel();
        listadmin = new javax.swing.JPanel();
        settings = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        dashpanel = new javax.swing.JPanel();
        dashboard1 = new javax.swing.JLabel();
        userpanel = new javax.swing.JPanel();
        users = new javax.swing.JLabel();
        mstaffpanel = new javax.swing.JPanel();
        mstaff = new javax.swing.JLabel();
        memployeepanel = new javax.swing.JPanel();
        memployee = new javax.swing.JLabel();
        servicepanel = new javax.swing.JPanel();
        service = new javax.swing.JLabel();
        bookingpanel = new javax.swing.JPanel();
        booking = new javax.swing.JLabel();
        reportspanel = new javax.swing.JPanel();
        review = new javax.swing.JLabel();
        reports = new javax.swing.JLabel();
        paymentpanel = new javax.swing.JPanel();
        payment = new javax.swing.JLabel();
        approvepanel = new javax.swing.JPanel();
        approve = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(232, 230, 230));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 45, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lg.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lg.setForeground(new java.awt.Color(239, 234, 234));
        lg.setText("Log Out");
        jPanel1.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, 20));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout (2).png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 30, 20));

        admindashboard.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        admindashboard.setForeground(new java.awt.Color(239, 234, 234));
        admindashboard.setText("Services");
        jPanel1.add(admindashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 50));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 640, 50));

        jPanel2.setBackground(new java.awt.Color(29, 45, 61));
        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 160, 110));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service ID", "Services", "Price", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 117, 450, 400));

        addpanel.setBackground(new java.awt.Color(29, 45, 61));
        addpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addpanelMouseClicked(evt);
            }
        });

        add.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(239, 234, 234));
        add.setText("ADD");
        addpanel.add(add);

        jPanel4.add(addpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 60, 30));

        editpanel.setBackground(new java.awt.Color(29, 45, 61));
        editpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editpanelMouseClicked(evt);
            }
        });

        edit.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(239, 234, 234));
        edit.setText("EDIT");
        editpanel.add(edit);

        jPanel4.add(editpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 60, 30));

        deletepanel.setBackground(new java.awt.Color(29, 45, 61));
        deletepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletepanelMouseClicked(evt);
            }
        });

        delete.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        delete.setForeground(new java.awt.Color(239, 234, 234));
        delete.setText("DELETE");
        deletepanel.add(delete);

        jPanel4.add(deletepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 60, 30));

        searchfield.setBackground(new java.awt.Color(29, 45, 61));
        searchfield.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        searchfield.setForeground(new java.awt.Color(255, 255, 255));
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        searchfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchfieldKeyTyped(evt);
            }
        });
        jPanel4.add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 160, 30));

        search.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        search.setText("SEARCH");
        jPanel4.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 60, 50));

        listadmin.setBackground(new java.awt.Color(55, 86, 93));
        listadmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings.setBackground(new java.awt.Color(255, 255, 255));
        settings.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        settings.setText("ACCOUNT");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        listadmin.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 10, 290, 50));

        lblUsername.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsername.setText("ADMIN");
        listadmin.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        dashpanel.setBackground(new java.awt.Color(29, 45, 61));
        dashpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        dashboard1.setForeground(new java.awt.Color(239, 234, 234));
        dashboard1.setText("Dashboard");
        dashpanel.add(dashboard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        listadmin.add(dashpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 160, 40));

        userpanel.setBackground(new java.awt.Color(29, 45, 61));
        userpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpanelMouseClicked(evt);
            }
        });
        userpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        users.setBackground(new java.awt.Color(29, 45, 61));
        users.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        users.setForeground(new java.awt.Color(239, 234, 234));
        users.setText("Users");
        userpanel.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, -1));

        listadmin.add(userpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 40));

        mstaffpanel.setBackground(new java.awt.Color(29, 45, 61));
        mstaffpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mstaff.setBackground(new java.awt.Color(212, 226, 240));
        mstaff.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        mstaff.setForeground(new java.awt.Color(239, 234, 234));
        mstaff.setText("Manage Staff");
        mstaffpanel.add(mstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        listadmin.add(mstaffpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 160, 40));

        memployeepanel.setBackground(new java.awt.Color(29, 45, 61));
        memployeepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memployee.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        memployee.setForeground(new java.awt.Color(239, 234, 234));
        memployee.setText("Manage Employee");
        memployeepanel.add(memployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, -1));

        listadmin.add(memployeepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 40));

        servicepanel.setBackground(new java.awt.Color(29, 45, 61));
        servicepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        service.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        service.setForeground(new java.awt.Color(239, 234, 234));
        service.setText("Services");
        servicepanel.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        listadmin.add(servicepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 160, 40));

        bookingpanel.setBackground(new java.awt.Color(29, 45, 61));
        bookingpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booking.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        booking.setForeground(new java.awt.Color(239, 234, 234));
        booking.setText("Booking");
        bookingpanel.add(booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        listadmin.add(bookingpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 160, 40));

        reportspanel.setBackground(new java.awt.Color(29, 45, 61));
        reportspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        review.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        reportspanel.add(review, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));

        reports.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        reports.setForeground(new java.awt.Color(239, 234, 234));
        reports.setText("Reports");
        reportspanel.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, -1));

        listadmin.add(reportspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 160, 40));

        paymentpanel.setBackground(new java.awt.Color(29, 45, 61));
        paymentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payment.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        payment.setForeground(new java.awt.Color(239, 234, 234));
        payment.setText("Payment");
        paymentpanel.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        listadmin.add(paymentpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 160, 40));

        jPanel4.add(listadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        approvepanel.setBackground(new java.awt.Color(29, 45, 61));
        approvepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approvepanelMouseClicked(evt);
            }
        });

        approve.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        approve.setForeground(new java.awt.Color(239, 234, 234));
        approve.setText("APPROVE");
        approvepanel.add(approve);

        jPanel4.add(approvepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 70, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
     public void loadTable(String keyword) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // Ensure s_status column exists (safe to call every time)
        ensureStatusColumn();

        String sql = "SELECT s_id, s_name, s_price, s_status FROM tbl_services "
                   + "WHERE s_name LIKE ? ORDER BY s_id";
        try (Connection con = config.connectDB();
             PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, "%" + keyword + "%");
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("s_id"),
                        rs.getString("s_name"),
                        rs.getInt("s_price"),
                        rs.getString("s_status") != null ? rs.getString("s_status") : "Active"
                    });
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error loading services:\n" + e.getMessage(),
                "DB Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** Adds s_status column to tbl_services if it does not exist yet. */
    private void ensureStatusColumn() {
        try (Connection con = config.connectDB();
             PreparedStatement ps = con.prepareStatement(
                 "ALTER TABLE tbl_services ADD COLUMN s_status TEXT DEFAULT 'Active'")) {
            ps.executeUpdate();
            // Also set any NULL rows to Active
            try (PreparedStatement ps2 = con.prepareStatement(
                     "UPDATE tbl_services SET s_status = 'Active' WHERE s_status IS NULL")) {
                ps2.executeUpdate();
            }
        } catch (SQLException e) {
            // Column already exists — safe to ignore
        }
    }

    /** Toggle the selected service between Active and Inactive. */
    private void toggleServiceStatus() {
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a service to toggle status.",
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int    id            = ((Number) model.getValueAt(row, 0)).intValue();
        String name          = (String)  model.getValueAt(row, 1);
        String currentStatus = String.valueOf(model.getValueAt(row, 3));
        String newStatus     = "Active".equalsIgnoreCase(currentStatus) ? "Inactive" : "Active";

        int confirm = JOptionPane.showConfirmDialog(this,
            "Set \"" + name + "\" status to " + newStatus + "?",
            "Confirm", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            conf.updateRecord(
                "UPDATE tbl_services SET s_status = ? WHERE s_id = ?",
                newStatus, id);
            JOptionPane.showMessageDialog(this,
                "\"" + name + "\" is now " + newStatus + ".",
                "Updated", JOptionPane.INFORMATION_MESSAGE);
            loadTable(searchfield.getText().trim());
        }
    }
    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        Profile a = new Profile();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsMouseClicked

    private void userpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpanelMouseClicked
        // Open List of Users
        Listofusers lou = new Listofusers();
        lou.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userpanelMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
         int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to log out?",
            "Log Out", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Session.getInstance().logout();
            LoginForm lf = new LoginForm();
            lf.setVisible(true);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void addpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpanelMouseClicked
         // Open ServiceForm in ADD mode (id = 0)
        ServiceForm sf = new ServiceForm(0, "", 0, this);
        sf.setVisible(true);
    }//GEN-LAST:event_addpanelMouseClicked

    private void editpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editpanelMouseClicked
       int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a service to edit.",
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int    id     = ((Number) model.getValueAt(row, 0)).intValue();
        String name   = (String)  model.getValueAt(row, 1);
        int    price  = ((Number) model.getValueAt(row, 2)).intValue();
        String status = String.valueOf(model.getValueAt(row, 3));

        // Open ServiceForm in EDIT mode
        ServiceForm sf = new ServiceForm(id, name, price, status, this);
        sf.setVisible(true);
    }//GEN-LAST:event_editpanelMouseClicked

    private void deletepanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepanelMouseClicked
      int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                "Please select a service to delete.",
                "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int    id   = ((Number) model.getValueAt(row, 0)).intValue();
        String name = (String)  model.getValueAt(row, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Delete service: \"" + name + "\" ?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            conf.deleteRecord("DELETE FROM tbl_services WHERE s_id = ?", id);
            JOptionPane.showMessageDialog(this,
                "\"" + name + "\" deleted successfully.",
                "Deleted", JOptionPane.INFORMATION_MESSAGE);
            loadTable(searchfield.getText().trim());
        }
    }//GEN-LAST:event_deletepanelMouseClicked

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
       
    }//GEN-LAST:event_searchfieldActionPerformed

    private void searchfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchfieldKeyTyped
        loadTable(searchfield.getText().trim());
    }//GEN-LAST:event_searchfieldKeyTyped

    private void approvepanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approvepanelMouseClicked
        toggleServiceStatus();
    }//GEN-LAST:event_approvepanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Session session = Session.getInstance();
        if (!session.isLoggedIn()) {
            JOptionPane.showMessageDialog(null,
                "Please login first!",
                "Unauthorized Access",
                JOptionPane.WARNING_MESSAGE);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginForm().setVisible(true);
                }
            });
            return;
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JPanel addpanel;
    private javax.swing.JLabel admindashboard;
    private javax.swing.JLabel approve;
    private javax.swing.JPanel approvepanel;
    private javax.swing.JLabel booking;
    private javax.swing.JPanel bookingpanel;
    private javax.swing.JLabel dashboard1;
    private javax.swing.JPanel dashpanel;
    private javax.swing.JLabel delete;
    private javax.swing.JPanel deletepanel;
    private javax.swing.JLabel edit;
    private javax.swing.JPanel editpanel;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lg;
    private javax.swing.JPanel listadmin;
    private javax.swing.JLabel memployee;
    private javax.swing.JPanel memployeepanel;
    private javax.swing.JLabel mstaff;
    private javax.swing.JPanel mstaffpanel;
    private javax.swing.JLabel payment;
    private javax.swing.JPanel paymentpanel;
    private javax.swing.JLabel reports;
    private javax.swing.JPanel reportspanel;
    private javax.swing.JLabel review;
    private javax.swing.JLabel search;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel service;
    private javax.swing.JPanel servicepanel;
    private javax.swing.JLabel settings;
    private javax.swing.JPanel userpanel;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables

    private void loadUsers(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
